# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.15

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/local/bin/cmake

# The command to remove a file.
RM = /usr/local/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/zhivar/Documents/university/AP_TA/AP_TA_EXAM

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/zhivar/Documents/university/AP_TA/AP_TA_EXAM

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/local/bin/cmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/local/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/zhivar/Documents/university/AP_TA/AP_TA_EXAM/CMakeFiles /home/zhivar/Documents/university/AP_TA/AP_TA_EXAM/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/zhivar/Documents/university/AP_TA/AP_TA_EXAM/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named AP_TA_EXAM

# Build rule for target.
AP_TA_EXAM: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 AP_TA_EXAM
.PHONY : AP_TA_EXAM

# fast build rule for target.
AP_TA_EXAM/fast:
	$(MAKE) -f CMakeFiles/AP_TA_EXAM.dir/build.make CMakeFiles/AP_TA_EXAM.dir/build
.PHONY : AP_TA_EXAM/fast

Input_handler/Input_handler.o: Input_handler/Input_handler.cpp.o

.PHONY : Input_handler/Input_handler.o

# target to build an object file
Input_handler/Input_handler.cpp.o:
	$(MAKE) -f CMakeFiles/AP_TA_EXAM.dir/build.make CMakeFiles/AP_TA_EXAM.dir/Input_handler/Input_handler.cpp.o
.PHONY : Input_handler/Input_handler.cpp.o

Input_handler/Input_handler.i: Input_handler/Input_handler.cpp.i

.PHONY : Input_handler/Input_handler.i

# target to preprocess a source file
Input_handler/Input_handler.cpp.i:
	$(MAKE) -f CMakeFiles/AP_TA_EXAM.dir/build.make CMakeFiles/AP_TA_EXAM.dir/Input_handler/Input_handler.cpp.i
.PHONY : Input_handler/Input_handler.cpp.i

Input_handler/Input_handler.s: Input_handler/Input_handler.cpp.s

.PHONY : Input_handler/Input_handler.s

# target to generate assembly for a file
Input_handler/Input_handler.cpp.s:
	$(MAKE) -f CMakeFiles/AP_TA_EXAM.dir/build.make CMakeFiles/AP_TA_EXAM.dir/Input_handler/Input_handler.cpp.s
.PHONY : Input_handler/Input_handler.cpp.s

Kids/Angry_kid.o: Kids/Angry_kid.cpp.o

.PHONY : Kids/Angry_kid.o

# target to build an object file
Kids/Angry_kid.cpp.o:
	$(MAKE) -f CMakeFiles/AP_TA_EXAM.dir/build.make CMakeFiles/AP_TA_EXAM.dir/Kids/Angry_kid.cpp.o
.PHONY : Kids/Angry_kid.cpp.o

Kids/Angry_kid.i: Kids/Angry_kid.cpp.i

.PHONY : Kids/Angry_kid.i

# target to preprocess a source file
Kids/Angry_kid.cpp.i:
	$(MAKE) -f CMakeFiles/AP_TA_EXAM.dir/build.make CMakeFiles/AP_TA_EXAM.dir/Kids/Angry_kid.cpp.i
.PHONY : Kids/Angry_kid.cpp.i

Kids/Angry_kid.s: Kids/Angry_kid.cpp.s

.PHONY : Kids/Angry_kid.s

# target to generate assembly for a file
Kids/Angry_kid.cpp.s:
	$(MAKE) -f CMakeFiles/AP_TA_EXAM.dir/build.make CMakeFiles/AP_TA_EXAM.dir/Kids/Angry_kid.cpp.s
.PHONY : Kids/Angry_kid.cpp.s

Kids/Coward_kid.o: Kids/Coward_kid.cpp.o

.PHONY : Kids/Coward_kid.o

# target to build an object file
Kids/Coward_kid.cpp.o:
	$(MAKE) -f CMakeFiles/AP_TA_EXAM.dir/build.make CMakeFiles/AP_TA_EXAM.dir/Kids/Coward_kid.cpp.o
.PHONY : Kids/Coward_kid.cpp.o

Kids/Coward_kid.i: Kids/Coward_kid.cpp.i

.PHONY : Kids/Coward_kid.i

# target to preprocess a source file
Kids/Coward_kid.cpp.i:
	$(MAKE) -f CMakeFiles/AP_TA_EXAM.dir/build.make CMakeFiles/AP_TA_EXAM.dir/Kids/Coward_kid.cpp.i
.PHONY : Kids/Coward_kid.cpp.i

Kids/Coward_kid.s: Kids/Coward_kid.cpp.s

.PHONY : Kids/Coward_kid.s

# target to generate assembly for a file
Kids/Coward_kid.cpp.s:
	$(MAKE) -f CMakeFiles/AP_TA_EXAM.dir/build.make CMakeFiles/AP_TA_EXAM.dir/Kids/Coward_kid.cpp.s
.PHONY : Kids/Coward_kid.cpp.s

Kids/Kid.o: Kids/Kid.cpp.o

.PHONY : Kids/Kid.o

# target to build an object file
Kids/Kid.cpp.o:
	$(MAKE) -f CMakeFiles/AP_TA_EXAM.dir/build.make CMakeFiles/AP_TA_EXAM.dir/Kids/Kid.cpp.o
.PHONY : Kids/Kid.cpp.o

Kids/Kid.i: Kids/Kid.cpp.i

.PHONY : Kids/Kid.i

# target to preprocess a source file
Kids/Kid.cpp.i:
	$(MAKE) -f CMakeFiles/AP_TA_EXAM.dir/build.make CMakeFiles/AP_TA_EXAM.dir/Kids/Kid.cpp.i
.PHONY : Kids/Kid.cpp.i

Kids/Kid.s: Kids/Kid.cpp.s

.PHONY : Kids/Kid.s

# target to generate assembly for a file
Kids/Kid.cpp.s:
	$(MAKE) -f CMakeFiles/AP_TA_EXAM.dir/build.make CMakeFiles/AP_TA_EXAM.dir/Kids/Kid.cpp.s
.PHONY : Kids/Kid.cpp.s

Kids/Peaceful_kid.o: Kids/Peaceful_kid.cpp.o

.PHONY : Kids/Peaceful_kid.o

# target to build an object file
Kids/Peaceful_kid.cpp.o:
	$(MAKE) -f CMakeFiles/AP_TA_EXAM.dir/build.make CMakeFiles/AP_TA_EXAM.dir/Kids/Peaceful_kid.cpp.o
.PHONY : Kids/Peaceful_kid.cpp.o

Kids/Peaceful_kid.i: Kids/Peaceful_kid.cpp.i

.PHONY : Kids/Peaceful_kid.i

# target to preprocess a source file
Kids/Peaceful_kid.cpp.i:
	$(MAKE) -f CMakeFiles/AP_TA_EXAM.dir/build.make CMakeFiles/AP_TA_EXAM.dir/Kids/Peaceful_kid.cpp.i
.PHONY : Kids/Peaceful_kid.cpp.i

Kids/Peaceful_kid.s: Kids/Peaceful_kid.cpp.s

.PHONY : Kids/Peaceful_kid.s

# target to generate assembly for a file
Kids/Peaceful_kid.cpp.s:
	$(MAKE) -f CMakeFiles/AP_TA_EXAM.dir/build.make CMakeFiles/AP_TA_EXAM.dir/Kids/Peaceful_kid.cpp.s
.PHONY : Kids/Peaceful_kid.cpp.s

Mad_house/Mad_house.o: Mad_house/Mad_house.cpp.o

.PHONY : Mad_house/Mad_house.o

# target to build an object file
Mad_house/Mad_house.cpp.o:
	$(MAKE) -f CMakeFiles/AP_TA_EXAM.dir/build.make CMakeFiles/AP_TA_EXAM.dir/Mad_house/Mad_house.cpp.o
.PHONY : Mad_house/Mad_house.cpp.o

Mad_house/Mad_house.i: Mad_house/Mad_house.cpp.i

.PHONY : Mad_house/Mad_house.i

# target to preprocess a source file
Mad_house/Mad_house.cpp.i:
	$(MAKE) -f CMakeFiles/AP_TA_EXAM.dir/build.make CMakeFiles/AP_TA_EXAM.dir/Mad_house/Mad_house.cpp.i
.PHONY : Mad_house/Mad_house.cpp.i

Mad_house/Mad_house.s: Mad_house/Mad_house.cpp.s

.PHONY : Mad_house/Mad_house.s

# target to generate assembly for a file
Mad_house/Mad_house.cpp.s:
	$(MAKE) -f CMakeFiles/AP_TA_EXAM.dir/build.make CMakeFiles/AP_TA_EXAM.dir/Mad_house/Mad_house.cpp.s
.PHONY : Mad_house/Mad_house.cpp.s

Map_handler/Map_handler.o: Map_handler/Map_handler.cpp.o

.PHONY : Map_handler/Map_handler.o

# target to build an object file
Map_handler/Map_handler.cpp.o:
	$(MAKE) -f CMakeFiles/AP_TA_EXAM.dir/build.make CMakeFiles/AP_TA_EXAM.dir/Map_handler/Map_handler.cpp.o
.PHONY : Map_handler/Map_handler.cpp.o

Map_handler/Map_handler.i: Map_handler/Map_handler.cpp.i

.PHONY : Map_handler/Map_handler.i

# target to preprocess a source file
Map_handler/Map_handler.cpp.i:
	$(MAKE) -f CMakeFiles/AP_TA_EXAM.dir/build.make CMakeFiles/AP_TA_EXAM.dir/Map_handler/Map_handler.cpp.i
.PHONY : Map_handler/Map_handler.cpp.i

Map_handler/Map_handler.s: Map_handler/Map_handler.cpp.s

.PHONY : Map_handler/Map_handler.s

# target to generate assembly for a file
Map_handler/Map_handler.cpp.s:
	$(MAKE) -f CMakeFiles/AP_TA_EXAM.dir/build.make CMakeFiles/AP_TA_EXAM.dir/Map_handler/Map_handler.cpp.s
.PHONY : Map_handler/Map_handler.cpp.s

main.o: main.cpp.o

.PHONY : main.o

# target to build an object file
main.cpp.o:
	$(MAKE) -f CMakeFiles/AP_TA_EXAM.dir/build.make CMakeFiles/AP_TA_EXAM.dir/main.cpp.o
.PHONY : main.cpp.o

main.i: main.cpp.i

.PHONY : main.i

# target to preprocess a source file
main.cpp.i:
	$(MAKE) -f CMakeFiles/AP_TA_EXAM.dir/build.make CMakeFiles/AP_TA_EXAM.dir/main.cpp.i
.PHONY : main.cpp.i

main.s: main.cpp.s

.PHONY : main.s

# target to generate assembly for a file
main.cpp.s:
	$(MAKE) -f CMakeFiles/AP_TA_EXAM.dir/build.make CMakeFiles/AP_TA_EXAM.dir/main.cpp.s
.PHONY : main.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... rebuild_cache"
	@echo "... AP_TA_EXAM"
	@echo "... edit_cache"
	@echo "... Input_handler/Input_handler.o"
	@echo "... Input_handler/Input_handler.i"
	@echo "... Input_handler/Input_handler.s"
	@echo "... Kids/Angry_kid.o"
	@echo "... Kids/Angry_kid.i"
	@echo "... Kids/Angry_kid.s"
	@echo "... Kids/Coward_kid.o"
	@echo "... Kids/Coward_kid.i"
	@echo "... Kids/Coward_kid.s"
	@echo "... Kids/Kid.o"
	@echo "... Kids/Kid.i"
	@echo "... Kids/Kid.s"
	@echo "... Kids/Peaceful_kid.o"
	@echo "... Kids/Peaceful_kid.i"
	@echo "... Kids/Peaceful_kid.s"
	@echo "... Mad_house/Mad_house.o"
	@echo "... Mad_house/Mad_house.i"
	@echo "... Mad_house/Mad_house.s"
	@echo "... Map_handler/Map_handler.o"
	@echo "... Map_handler/Map_handler.i"
	@echo "... Map_handler/Map_handler.s"
	@echo "... main.o"
	@echo "... main.i"
	@echo "... main.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

